# This module tries to find the LHAPDF installation on your system.

MESSAGE(STATUS "Looking for cfitsio...")

FIND_LIBRARY(CFITSIO_LIBRARIES
  NAMES
  cfitsio
  PATHS
 # $ENV{CFITSIO_PATH}/lib
  ${CFITSIO_PATH}/lib
  )
#MESSAGE(STATUS "HALLO $ENV{CFITSIO_PATH} uu ${CFITSIO_LIBRARIES}" )
MESSAGE(STATUS "HALLO ${CFITSIO_PATH} uu ${CFITSIO_LIBRARIES}" )


FIND_PATH(CFITSIO_INCLUDE_DIR
 fitsio.h
# $ENV{CFITSIO_PATH}/include
 ${CFITSIO_PATH}/include
 )
#MESSAGE(STATUS "HALLO $ENV{CFITSIO_PATH} uu ${CFITSIO_INCLUDE}" )
MESSAGE(STATUS "HALLO ${CFITSIO_PATH} uu ${CFITSIO_INCLUDE_DIR}" )
